### ISSUE TITLE
BEGIN-COMMIT is a migration

### ISSUE THREAD

**Issue by rpavlovs** [sequelize/umzug#124]
Hi,

I have a problem with `BEGIN-COMMIT` keywords in a migration.

I run `umzug.up()` for all of my migrations in a loop, and log errors if they occur. Unfortunately, as soon as umzug gets to this one:
```
BEGIN;
...
# Some SQL that produces an error
...
COMMIT;
```
 all the next migrations error out with:
```
SequelizeDatabaseError: current transaction is aborted, commands ignored until end of transaction block
```

Is there a way to run migrations atomically with umzug?

Thanks

**Comment by jukkah** [comment]
Well, I think this is not an issue of umzug. `umzug.up()` basically only calls `up` method for each migration file. As umzug is framework agnostic, it doesn't care what is in these methods.

So, you run Sequelize's [queryInterface functions](http://docs.sequelizejs.com/en/v3/docs/migrations/) in your migration files? The problem is that you can't run queryInterfaces functions as you would like. Try to combine your migration files into single file and you should see the same error.

**Comment by rpavlovs** [comment]
I found that `BEGIN-COMMIT` interferes with Sequelize's build-in transactions. I've changed my script rely on Sequelize for atomicity.
