### ISSUE TITLE
umzug.up({to: '...'}) runs all pending migrations instead of only those from the current state to the given name

### ISSUE THREAD

**Issue by rgrove** [sequelize/umzug#36]
According to the readme:

> It is also possible to pass the name of a migration in order to just run the migrations from the current state to the passed migration name.
>
>     umzug.up({ to: '20141101203500-task' }).then(function (migrations) {});

However, this doesn't appear to work as described. Using umzug 1.6.0, when I pass an options object like `{to: '201510301204-add-index'}`, umzug runs _all_ pending migrations, not just the migrations between the current state and `201510301204-add-index`. It also runs all pending migrations if I pass a completely bogus migration name like `{to: 'bogus'}`.

I peeked at the unit tests to see if they held any clues, but passing an options object to `up()` doesn't seem to be tested. Does this feature actually exist?

**Comment by jukkah** [comment]
It seems that the feature has been implemented before v1.6.0, so it exists. It is implemented in `umzug._findMigrationsUntilMatch`. There is even tests for `umzug.up` and `umzug.down` with name '_when `to` option is passed_' in files test/index/up.test.js and test/index/down.test.js.

In a week, I'll try to figure out how is it working and check if there is a bug or not.

**Comment by sdepold** [comment]
@jukkah I sense a good amount of interest in this project?! I'm excited

**Comment by sdepold** [comment]
https://github.com/sequelize/umzug/blob/master/test/index/up.test.js#L77-L105 @rgrove

**Comment by rgrove** [comment]
Hmm. If those tests are passing, then I guess I can't explain the behavior I was seeing. I couldn't get the `to` option to limit my migrations no matter what I tried. In any event, I ended up not using MySQL for this project after all, so it's a moot point for me now.

Thanks for the help!

**Comment by jukkah** [comment]
I found one potential problem.

Lets say we have migrations `1-migration`, `2-migration`, and `3-migration`. If `1-migration` is executed, calling `umzug.up({to: '1-migration'})` executes all the pending migrations because pending migrations doesn't contain `1-migration`. Also, calling `umzug.up({to: 'bogus'})` does the same.

I think, in these cases no migrations should be executed. It would be nice to log something like 'Migration 1-migration has already been executed. Aborting...' and 'Migration bogus not found. Aborting...'.

@rgrove This explains your bogus example but not your original problem. The only solution I can see is that you tried to remigrate to an already migrated point.

**Comment by rgrove** [comment]
@jukkah Thanks for investigating! I definitely saw this while trying to remigrate to an already migrated point, but my memory is hazy on whether I also tried reproducing the issue from a clean state. I think the issue you fixed is probably what I was seeing though.
