### ISSUE TITLE
Database changelog lock table support

### ISSUE THREAD

**Issue by pragmaticivan** [sequelize/umzug#487]
Thoughts on implementing something similar to that feature in liquibase?

https://docs.liquibase.com/concepts/basic/databasechangeloglock-table.html

------
Database Change Lock
Another way Liquibase supports this pattern is to include a locking mechanism. This lock ensures that if multiple servers start simultaneously, they won’t run into problems as they both try to apply the same database changes. 

The locking system uses a DATABASECHANGELOGLOCK table as the synchronization point, with the service setting the LOCKED column to 1 when it takes the lock and setting it to 0 when it finishes. 

As long as the process that has set the LOCKED column to 1 isn’t killed before it has a chance to set back to 0, this works fine. When it’s not working fine, all of the other Liquibase processes (including a newly restarted process on the same machine) will just continue to wait for a 0 value which will never come. The only way to recover from this scenario is by running the Liquibase unlock command or updating the DATABASECHANGELOGLOCK table manually.

**Comment by mmkal** [comment]
This is unlikely to be part of umzug as things stand, because locking varies a lot between database systems. Last I checked there wasn't a clear way to do this via sequelize. It's possible to achieve this on the user side, though. Here's how [@slonik/migrator](https://npmjs.com/package/@slonik/migrator) does this by overriding the `runCommand` method, and uses `pg_advisory_lock`: https://github.com/mmkal/slonik-tools/blob/e88bfaab73cd2f8033d0d23551330ad23fd30191/packages/migrator/src/index.ts#L140-L170

**Comment by pragmaticivan** [comment]
Sounds good.
